### ISSUE TITLE
Can not find sootclasses-2.4.0-mine.jar 

### ISSUE THREAD

**Issue by DhritiKhanna** [nunomachado/cortex-tool#1]
Is this jar file any different from soot jar from sable group: https://www.sable.mcgill.ca/soot/soot_download.html?

**Comment by nunomachado** [comment]
I've just pushed the Soot jars used during the development of Cortex. Can you pull the latest version of the repo and check if the instrumentation works?

**Comment by DhritiKhanna** [comment]
Yes. Thank you.
